name: jaguar_orm_gen
description: Generator for jaguar_orm
version: 2.2.30
homepage: https://github.com/Jaguar-dart/jaguar_orm

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  jaguar_query: #^2.2.9
    path: ../query
  jaguar_orm: #^2.2.7
    path: ../orm
  analyzer: ^5.13.0
  build: ^2.4.1
  logging: ^1.2.0
  source_gen: ^1.4.0
  meta: ^1.9.1
  collection: ^1.17.2

dependency_overrides:
  jaguar_orm:
    path: ../orm
  jaguar_query:
    path: ../query

dev_dependencies:
  test: ^1.24.6
  build_runner: ^2.2.1
  build_test: ^2.1.0
  path: ^1.8.0
